server:
  port: 9290

spring:
  datasource:
    username: root
    password: ypf123
    url: jdbc:mysql://localhost:3306/store
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  redis:
    database: 0
    host: localhost
    port: 6379
  application:
    name: store
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

mybatis-plus:

  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    db-config:
      id-type: auto
#  global-config:
#    db-config:
#      table-underline: false
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#开启日志
logging:
  level:
    root: info

file-save-path: D:/images/